spring.application.name=nfl-history-api
#
spring.datasource.url=jdbc:postgresql://localhost:5432/nfl_history
spring.datasource.username=postgres
spring.datasource.password=USSGuamlph9#
spring.datasource.driver-class-name=org.postgresql.Driver